### PR TITLE
https://jira.fkinternal.com/browse/DFORTYTWO-1429:	Extended Logging Changes(Incomplete and suspended for now).

### PR DESCRIPTION
**Pull request by souravchk**
Just for viewing purposes. Changes saved for any future endeavours.

### CODE REVIEW

**Comment by jecluis** [comment]
This pull request's title has an internal URL as its title. Can you please change it to something consumable for anyone not in your internal network? (or maybe just drop the url) :)

**Comment by souravchk** [comment]
Hi sir,

Sorry. This PR is a misoperation. Never mind.

**Comment by jecluis** [comment]
Do you intend it to be closed, or something else?

**Comment by souravchk** [comment]
Yes. Close it. It was by mistake.

**Pull request closed without merging**
