### PR TITLE
Make MAX_REQUEST_SIZE configurable

### PR DESCRIPTION
**Pull request by big-henry**
In case we want to support larger S3 object metadata, we need to
increase the MAX_REQUEST_SIZE of civetweb. Make it configurable.

Signed-off-by: Henry Chang <henry_chang@bigtera.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
Has this gone into [civetweb upstream](https://github.com/civetweb/civetweb)?

**Comment by big-henry** [comment]
No. Should I submit to civetweb upstream instead?

**Comment by cbodley** [comment]
> No. Should I submit to civetweb upstream instead?

yes please! the fewer changes we have to maintain in our fork, the easier it is to keep up with upstream civetweb

**Comment by cbodley** [comment]
@big-henry I created a feature request at http://tracker.ceph.com/issues/20094 so we can track the progress. Once you submit an upstream pull request, can you please add a link to that pr in the ticket?

**Comment by big-henry** [comment]
Sure. Thanks.

**Pull request closed without merging**
